AWSTemplateFormatVersion: '2010-09-09'
Description: "meshify sns"
Resources:
  MESHIFYsnssendmailFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: MESHIFY_sns_sendmail
      Handler: index.handler
      Role:
        Fn::GetAtt: [ LambdaRole , Arn ]
      Runtime: nodejs6.10
      Timeout: 300
      Environment:
        Variables:
          ACCOUNTID:
            Ref: AWS::AccountId
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
            - Effect: Allow
              Action:
              - SNS:Publish
              - SNS:CreateTopic
              - SNS:Subscribe
              Resource: "*"
  InvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS:
            - 321232316075
            - 184705290838
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - lambda:InvokeFunction
              Resource:
                Fn::GetAtt: [ MESHIFYsnssendmailFunction , Arn ]
Outputs:
  MESHIFYsnssendmailFunction:
    Description: '/MESHIFY/MESHIFY/sns/sendmail/lambda'
    Value:
      Fn::GetAtt: [ MESHIFYsnssendmailFunction , Arn ]
  MESHIFYsnssendmailRole:
    Description: '/MESHIFY/MESHIFY/sns/sendmail/role'
    Value:
      Fn::GetAtt: [ InvokeRole , Arn ]
